[versions]
kotlin = "1.9.10"
[libraries]
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
[plugins]
gradle-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }